### PR TITLE
Fix/248 legend formatting

### LINKED ISSUE #248: Multiple spikes in legend when only one spike on map
It's possible to have the first spike read 1, second spike read "N/A" and largest spike read 1.  

If there is only one spike to show on the map, we should only show one spike in the legend.

image

### LINKED ISSUE #249: Do not show legend when there is no data available
Currently on the immigration page, when there is no data available the legend still shows with spikes and values.

When there are no spikes on the map, we should not show a spike legend and instead give a "no data available" message.

In addition, it appears like there is some language missing here (e.g. see `map_tested_immigration` in the screenshot)

image

### PR DESCRIPTION
**Pull request by hoshmn**
Fixes #248 and fixes #249 (for all instances of MapLegend, not just Immigration). Also removes the `tested` metrics from Immigration map (which Liz requested, meant to do that before).

### CODE REVIEW

File: packages/gatsby-ucla-site/src/components/maps/MapLegend.js [hunk 1]
```diff
@@ -66,39 +72,51 @@ const SpikeLegend = ({ data, sizeRange = [1, 60] }) => {
...
-        <Typography className={classes.label} variant="body2">
-          {spikeLabels[2]}
+      {noValuesMapped ? (
+        <Typography variant="body2">
+          {getLang("empty_legend_message")}
         </Typography>
-      </Stack>
+      ) : (
+        <>
+          {!singleValueMapped && (
```
Comment (hoshmn) [inline packages/gatsby-ucla-site/src/components/maps/MapLegend.js:81]: net change of the `return`: render spikes & no data message conditionally
